#include "aead_hw.h"
#include "xparameters.h"
#include "xil_printf.h"

/* Replace this alias with the actual address name generated by Vivado/Vitis. */
#ifndef XPAR_AEAD_AXI_BASEADDR
#define XPAR_AEAD_AXI_BASEADDR 0x43C00000u
#endif

int main(void)
{
    static const uint8_t tx_key[32] = {
        0x71,0x73,0x2b,0xda,0xfb,0x22,0xb7,0xdc,
        0xc9,0x49,0xf0,0x90,0x2c,0x5e,0xf4,0x20,
        0xc1,0x6a,0x94,0x56,0x33,0xdc,0x87,0xe5,
        0x79,0xfe,0x9e,0x5b,0x77,0x55,0x11,0x4a
    };
    static const uint8_t prefix[4] = {0x7d,0x3f,0xe8,0x4c};
    static const uint8_t message[] = "ZedBoard ML-KEM + ChaCha20-Poly1305 demo";
    uint8_t ciphertext[64];
    uint8_t plaintext[64];
    uint8_t tag[16];
    uint64_t counter;
    aead_hw_t device;
    int result;

    aead_hw_init(&device, XPAR_AEAD_AXI_BASEADDR, 1000000u);

    /* Golden-vector example only. Final hardware must use distinct TX/RX KDF outputs. */
    result = aead_hw_configure_session(&device, 0u, 0x01020304u,
                                       tx_key, tx_key, prefix, prefix);
    if (result != AEAD_HW_OK) {
        xil_printf("session configuration failed: %d\r\n", result);
        return result;
    }

    result = aead_hw_encrypt(&device, 0u, message,
                             (uint8_t)(sizeof(message)-1u),
                             ciphertext, tag, &counter);
    if (result != AEAD_HW_OK) {
        xil_printf("encryption failed: %d\r\n", result);
        return result;
    }

    result = aead_hw_decrypt(&device, 0u, 0u,
                             (uint8_t)(sizeof(message)-1u),
                             ciphertext, tag, plaintext);
    xil_printf("decrypt result=%d, TX counter=%lu\r\n",
               result, (unsigned long)counter);
    return result;
}
